### ISSUE TITLE
회원가입 문의 건

### ISSUE THREAD

**Issue by Hamel0** [miracle-job-a/company-service#106]
- 기업이 회원 가입 시, 기업명과 대표자 가 영어를 기입하지 못 하게 되어있어서 영어 이름 회사나 외국인 대표자는 가입을 못 할 거 같습니다.
혹시 전에 의논 된 사항이 있었나요?

**Comment by Kade-Jeon** [comment]
<img width="610" alt="image" src="https://github.com/miracle-job-a/company-service/assets/58586365/a42c14cc-cdb9-43b9-93fe-74bb3ddfeeac">

잘되는 것으로 확인했습니다. 다시 한번 확인 부탁드립니다.
- 대표자명은 한글로만 받기로 함. (실제 외국기업도 국내 비즈니스 시 이렇게 됨)
- 회사명은 영어로 잘 됨.
