### ISSUE TITLE
DB에 sql문 최신화 부탁드립니당

### ISSUE THREAD

**Issue by kimjunyo** [miracle-job-a/company-service#53]
DB에는 password가 int로 되어 있는데 코드는 String으로 되어 있어요 ㅠ

**Comment by Kade-Jeon** [comment]
> DB에는 password가 int로 되어 있는데 코드는 String으로 되어 있어요 ㅠ

오늘 SHA-3 알고리즘으로 암호화 적용되서 바뀐 겁니다. DDL 쿼리문 추후 새로 전달 예정이며 일단은 비밀번호 쪽만 varchar(128)로 바꾸어 작업 부탁드립니다.

**Comment by kimjunyo** [comment]
넵

**Comment by Kade-Jeon** [comment]
아 아직 암호화 된게 푸시가 안된 상황이라 다시 알려드립니다. Password는 String으로 받고 그 String을 하시화 하여 숫자로 저장됩니다.
