### ISSUE TITLE
[제안] 공고 등록 하는 거에서 제안할 게 있습니다.

### ISSUE THREAD

**Issue by kimjunyo** [miracle-job-a/company-service#54]
공고 등록할 때 dto 안에 companyId가 있는데 url에 이미 pathvariable로 받고있는데
dto에 companyId가 없어도 될 꺼같아요.
다른 것들도 이렇게 중복된 내용들 있으면 확인 부탁드립니다.

**Comment by wjdals3936** [comment]
알겠습니다. 확인 후 다시 답변 드리겠습니다

**Comment by Kade-Jeon** [comment]
@kimjunyo 총 2개 Dto 수정하였습니다.

- CompnayFaqRequestDto 의 companyId 삭제
- postRequestDto 의 companyId 삭제

**Comment by kimjunyo** [comment]
확인하였습니다
