### ISSUE TITLE
공고 조회할 때 회사정보가 안옵니다..

### ISSUE THREAD

**Issue by kimjunyo** [miracle-job-a/company-service#65]
공고 조회할 때 회사명, 대표자명, 재직인원, 주소, 사진, 기업 소개가 와야 하는데.. 안옵니다
faqList도 넘겨줘야 합니다.. API 설명 참고바람.

**Comment by wjdals3936** [comment]
/v1/company/{companyId}/info 여기로 API 요청하시면 해당 데이터 가져오도록 구현되어 있습니다.

관련 백로그:
https://github.com/orgs/miracle-job-a/projects/3/views/9?pane=issue&itemId=44659428
