### ISSUE TITLE
Interceptor에 관한 질문

### ISSUE THREAD

**Issue by kimjunyo** [miracle-job-a/company-service#77]
Cannot invoke "String.equals(Object)" because "pathCompanyId" is null
방금 전에 pull 해서 받았는데 pathCompanyId를 못받는다고 에러가 뜨는데
혹시 어떻게 해결하면 될까요?

**Comment by wjdals3936** [comment]
확인해보겠습니다

**Comment by kimjunyo** [comment]
faq는 되는데 post는 안되는데 아마도 인터셉터 경로 문제 같습니다.

**Comment by wjdals3936** [comment]
어떤 API를 요청할 때 발생하는 오류인지 좀 더 자세히 알려주시면 다시 확인해보겠습니다.

**Comment by kimjunyo** [comment]
제가 /v1/company/{companyId}/posts/latest API 요청이었는데
interceptor에 있는 pathCompanyId가 null로 떠서 다시 반환이 되더군요.

.excludePathPatterns(baseUrl + "/{companyId:\\d+}/posts/latest")
이거를 인터셉터에서 뺐더니 작동이 잘 되는데 이렇게 진행해도 되나요?

**Comment by wjdals3936** [comment]
네 확인하겠습니다

**Comment by wjdals3936** [comment]
제가  확인해본 결과 코드에는 문제가 없는 것 같습니다.

다음 사항들을 확인 부탁드립니다.
1. API 요청시 header에 Session-Id와 Miracle 값이 정확한지
2. API요청시 url에 파라미터가 포함되어 있는지
> 예시: localhost:60002/v1/company/1/posts/latest?strNum=1&endNum=5

**Comment by wjdals3936** [comment]
네 확인했습니다.
