### ISSUE TITLE
유저 지원 목록(지원서)에서의 기업정보 api 요청

### ISSUE THREAD

**Issue by Hamel0** [miracle-job-a/company-service#94]
> 설명
- 유저가 지원한 목록을 보여주는 지원현황 목록에서, 공고 id를 가지고 있으나 기업정보를 알 수없음
- 공고 id로 기업의 정보를 조회하여 출력이 필요함

> 요청 api
- RequestData : 공고 id
- ResponseData : 기업 id, 기업 이름

> 특이사항
- admin에서 스택 매칭 한 것처럼 요청하고 받으면 될 거 같습니다..

**Comment by wjdals3936** [comment]
확인했습니다
